CREATE TABLE detecciones (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  latitude REAL DEFAULT NULL,
  longitude REAL DEFAULT NULL,
  brightness REAL DEFAULT NULL,
  scan REAL DEFAULT NULL,
  track REAL DEFAULT NULL,
  acq_date TEXT DEFAULT NULL,
  acq_time INTEGER DEFAULT NULL,
  satellite TEXT DEFAULT NULL,
  instrument TEXT DEFAULT 'MODIS',
  confidence INTEGER DEFAULT NULL,
  version TEXT DEFAULT NULL,
  bright_t31 REAL DEFAULT NULL,
  frp REAL DEFAULT NULL,
  daynight TEXT DEFAULT NULL,
  pais TEXT DEFAULT NULL
);